# IOTech Edge Xpert version: 2.0.3
version: "3.7"

networks:
  edgex-network:
    driver: bridge

volumes:
  db-data:
  license-data:
  influx-data:
  influx-config:
  grafana-data:
  mosquitto-log:
  mosquitto-data:
  device-modbus-data:
  device-opc-ua-data:
  app-influxdb-config:
  app-aws-modbus-config:
  app-aws-opc-ua-config:

# all common shared environment variables defined here:
x-common-env-variables: &common-variables
  EDGEX_SECURITY_SECRET_STORE: "false"
  CLIENTS_CORE_COMMAND_HOST: edgex-core-command
  CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
  DATABASES_PRIMARY_HOST: edgex-redis
  MESSAGEQUEUE_HOST: edgex-redis
  # license
  EDGEXPERT_LICENSE_PATH: /edgexpert/licenses/

services:

  #################################################################
  # Database Services
  #################################################################

  redis:
    image: redis:6.2.5-alpine
    container_name: redis
    hostname: edgex-redis
    networks:
      - edgex-network
    restart: always
    read_only: true
    security_opt:
      - no-new-privileges:true
    user: root:root
    volumes:
      - db-data:/data:z
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "5"

  #################################################################
  # Core Services
  #################################################################

  core-metadata:
    image: iotechsys/edgexpert-core-metadata:2.0
    container_name: core-metadata
    hostname: edgex-core-metadata
    ports:
      - "59881:59881"
    networks:
      - edgex-network
    restart: always
    read_only: true
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    environment:
      <<: *common-variables
      SERVICE_HOST: core-metadata
    volumes:
      - license-data:/edgexpert/licenses/:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "5"

  core-command:
    image: iotechsys/edgexpert-core-command:2.0
    container_name: core-command
    hostname: edgex-core-command
    ports:
      - "59882:59882"
    networks:
      - edgex-network
    restart: always
    read_only: true
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    environment:
      <<: *common-variables
      SERVICE_HOST: core-command
    volumes:
      - license-data:/edgexpert/licenses/:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "5"

  #################################################################
  # Device Services
  #################################################################

  device-modbus:
    image: iotechsys/edgexpert-device-modbus:2.0
    container_name: device-modbus
    hostname: device-modbus
    networks:
      - edgex-network
    ports:
      - "59901:59901"
    restart: always
    read_only: true
    user: 2002:2001
    environment:
      <<: *common-variables
      SERVICE_HOST: device-modbus
      XRTCONTROL_USEXRTSCHEDULE: "true"
      #WRITABLE_LOGLEVEL: "DEBUG"
    volumes:
      - license-data:/edgexpert/licenses/:ro
      - device-modbus-data:/opt/iotech/xrt/config
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "5"

  device-opc-ua:
    image: iotechsys/edgexpert-device-opc-ua:2.0
    container_name: device-opc-ua
    hostname: device-opc-ua
    networks:
      - edgex-network
    ports:
      - "59953:59953"
    restart: always
    read_only: true
    user: 2002:2001
    environment:
      <<: *common-variables
      SERVICE_HOST: device-opc-ua
      LDSName:
      DiscoveryCertificate:
      DiscoveryKey:
      DiscoveryUsername:
      DiscoveryPassword:
      XRTCONTROL_USEXRTSCHEDULE: "true"
      #WRITABLE_LOGLEVEL: "DEBUG"
    volumes:
      - license-data:/edgexpert/licenses/:ro
      - device-opc-ua-data:/opt/iotech/xrt/config
      # - ${CLIENT_KEYS_PATH}:/opt/iotech/xrt/config/keys
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "5"

  #################################################################
  # App Services
  #################################################################

  app-influxdb:
    image: iotechsys/edgexpert-app-configurable:2.0
    container_name: app-influxdb
    hostname: app-influxdb
    networks:
      - edgex-network
    command: "--confdir=/res --file=app-influxdb.toml"
    restart: always
    read_only: true
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    environment:
      <<: *common-variables
      SERVICE_HOST: app-influxdb
      DATABASE_HOST: edgex-redis
      TRIGGER_EDGEXMESSAGEBUS_SUBSCRIBEHOST_HOST: edgex-redis
      TRIGGER_EDGEXMESSAGEBUS_PUBLISHHOST_HOST: edgex-redis
    volumes:
      - app-influxdb-config:/res
      - license-data:/edgexpert/licenses/:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "5"

  app-aws-modbus:
    image: iotechsys/edgexpert-app-configurable:2.0
    container_name: app-aws-modbus
    hostname: app-aws-modbus
    networks:
      - edgex-network
    command: "--confdir=/res --file=app-aws-modbus.toml"
    restart: always
    read_only: true
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    environment:
      <<: *common-variables
      SERVICE_HOST: app-aws-modbus
      DATABASE_HOST: edgex-redis
      TRIGGER_EDGEXMESSAGEBUS_SUBSCRIBEHOST_HOST: edgex-redis
      TRIGGER_EDGEXMESSAGEBUS_PUBLISHHOST_HOST: edgex-redis
    volumes:
      - app-aws-modbus-config:/res
      - license-data:/edgexpert/licenses/:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "5"

  app-aws-opc-ua:
    image: iotechsys/edgexpert-app-configurable:2.0
    container_name: app-aws-opc-ua
    hostname: app-aws-opc-ua
    networks:
      - edgex-network
    command: "--confdir=/res --file=app-aws-opc-ua.toml"
    restart: always
    read_only: true
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    environment:
      <<: *common-variables
      SERVICE_HOST: app-aws-opc-ua
      DATABASE_HOST: edgex-redis
      TRIGGER_EDGEXMESSAGEBUS_SUBSCRIBEHOST_HOST: edgex-redis
      TRIGGER_EDGEXMESSAGEBUS_PUBLISHHOST_HOST: edgex-redis
    volumes:
      - app-aws-opc-ua-config:/res
      - license-data:/edgexpert/licenses/:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "5"


  #################################################################
  # Tools
  #################################################################

  mqtt-broker:
    command: "/usr/sbin/mosquitto -c /mosquitto-no-auth.conf"
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    hostname: mqtt-broker
    networks:
      - edgex-network
    ports:
      - "1883:1883"
    restart: always
    read_only: true
    user: 2002:2001
    volumes:
      - mosquitto-log:/mosquitto/log
      - mosquitto-data:/mosquitto/data
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "5"

  influxdb2:
    image: influxdb:2.0.8
    container_name: influxdb2
    hostname: influxdb2
    networks:
      - edgex-network
    restart: always
    user: influxdb:influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin-password
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: my-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: token
      # refer to https://docs.influxdata.com/influxdb/v2.0/reference/internals/shards 
      DOCKER_INFLUXDB_INIT_RETENTION: 24w 
    volumes:
      - influx-data:/var/lib/influxdb2
      - influx-config:/etc/influxdb2
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "5"

  grafana:
    image: grafana/grafana:8.1.2
    container_name: grafana
    hostname: edgex-grafana
    networks:
      edgex-network:
        aliases:
          - edgex-grafana
    ports:
      - "3000:3000"
    volumes:
      - type: volume
        source: grafana-data
        target: /var/lib/grafana
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

  #################################################################
  # Service Setup (Metadata, Export-Client, Grafana)
  #################################################################

  service-setup:
    image: iotechsys/edgexpert-demo-lua:large-signals-demo-x86_64
    container_name: service-setup
    hostname: service-setup
    read_only: true
    security_opt:
      - no-new-privileges:true
    networks:
      edgex-network:
        aliases:
          - service-setup
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "5"
    depends_on:
      - core-metadata
      - influxdb2
      - grafana


