{
 "title": "Chemical Tank Dashboard",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Modbus Tank Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5s)\n  |> filter(fn: (r) => r[\"resourceName\"] == \"Temperature\")\n  |> group(columns: [\"resourceName\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5s)\n  |> filter(fn: (r) => r[\"resourceName\"] == \"Pressure\")\n  |> group(columns: [\"resourceName\"])\n  |> sort(columns: [\"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Chemical Tank" },
      { "condition": "AND", "key": "resource_name", "operator": "=", "value": "Pressure" }
     ]
    }
   ]
  },
  {
   "title": "Live Tank Info",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Temperature",
     "measurement": "readings",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -3m)\n  |> filter(fn: (r) => r[\"resourceName\"] == \"Temperature\")\n  |> group(columns: [\"resourceName\"])\n  |> sort(columns: [\"_time\"])\n  |> drop(columns: [\"_field\", \"_measurement\", \"event_id\", \"deviceName\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Chemical Tank" },
      { "condition": "AND", "key": "resource_name", "operator": "=", "value": "Temperature" }
     ]
    },
    {
     "alias": "Pressure",
     "measurement": "readings",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -3m)\n  |> filter(fn: (r) => r[\"resourceName\"] == \"Pressure\")\n  |> group(columns: [\"resourceName\"])\n  |> sort(columns: [\"_time\"])\n  |> drop(columns: [\"_field\", \"_measurement\", \"event_id\", \"deviceName\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Chemical Tank" },
      { "condition": "AND", "key": "resource_name", "operator": "=", "value": "Pressure" }
     ]
    },
    {
     "alias": "Level",
     "measurement": "readings",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -3m)\n  |> filter(fn: (r) => r[\"resourceName\"] == \"Level\")\n  |> group(columns: [\"resourceName\"])\n  |> sort(columns: [\"_time\"])\n  |> drop(columns: [\"_field\", \"_measurement\", \"event_id\", \"deviceName\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Chemical Tank" },
      { "condition": "AND", "key": "resource_name", "operator": "=", "value": "Level" }
     ]
    }
   ]
  },
  {
   "title": "Temperature Table",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 5, "x": 18, "y": 1 },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -30s)\n  |> filter(fn: (r) => r[\"resourceName\"] == \"Temperature\")\n  |> group(columns: [\"resourceName\"])\n  |> sort(columns: [\"_time\"])\n  |> drop(columns: [\"_field\", \"_measurement\", \"event_id\", \"deviceName\"])\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Chemical Tank" },
      { "condition": "AND", "key": "resource_name", "operator": "=", "value": "Temperature" }
     ]
    }
   ]
  },
  {
   "title": "Min (last 30 secs)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -30s)\n  |> filter(fn: (r) => r[\"resourceName\"] == \"Temperature\")\n  |> group(columns: [\"resourceName\"])\n  |> sort(columns: [\"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Chemical Tank" },
      { "condition": "AND", "key": "resource_name", "operator": "=", "value": "Temperature" }
     ]
    }
   ]
  },
  {
   "title": "Mean (last 30 secs)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -30s)\n  |> filter(fn: (r) => r[\"resourceName\"] == \"Pressure\")\n  |> group(columns: [\"resourceName\"])\n  |> sort(columns: [\"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Chemical Tank" },
      { "condition": "AND", "key": "resource_name", "operator": "=", "value": "Pressure" }
     ]
    }
   ]
  },
  {
   "title": "Max (last 30 secs)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -30s)\n  |> filter(fn: (r) => r[\"resourceName\"] == \"Temperature\")\n  |> group(columns: [\"resourceName\"])\n  |> sort(columns: [\"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Chemical Tank" },
      { "condition": "AND", "key": "resource_name", "operator": "=", "value": "Temperature" }
     ]
    }
   ]
  },
  {
   "title": "Range (last 30 secs)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -30s)\n  |> filter(fn: (r) => r[\"resourceName\"] == \"Pressure\")\n  |> group(columns: [\"resourceName\"])\n  |> sort(columns: [\"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Chemical Tank" },
      { "condition": "AND", "key": "resource_name", "operator": "=", "value": "Pressure" }
     ]
    }
   ]
  },
  { "title": "OPC-UA Valve Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Setting",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -3s)\n  |> filter(fn: (r) => r[\"resourceName\"] == \"Setting\")\n  |> group(columns: [\"resourceName\"])\n  |> sort(columns: [\"_time\"])\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Outlet Valve" },
      { "condition": "AND", "key": "resource_name", "operator": "=", "value": "Setting" }
     ]
    }
   ]
  },
  {
   "title": "Live Valve Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Engine OPC UA",
     "measurement": "readings",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -3m)\n  |> filter(fn: (r) => r[\"resourceName\"] == \"Setting\")\n  |> group(columns: [\"resourceName\"])\n  |> sort(columns: [\"_time\"])\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Outlet Valve" },
      { "condition": "AND", "key": "resource_name", "operator": "=", "value": "Setting" }
     ]
    }
   ]
  },
  {
   "title": "Setting Table",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 12 },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -30s)\n  |> filter(fn: (r) => r[\"resourceName\"] == \"Setting\")\n  |> group(columns: [\"resourceName\"])\n  |> sort(columns: [\"_time\"])\n  |> drop(columns: [\"_field\", \"_measurement\", \"event_id\", \"deviceName\"])\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Outlet Valve" },
      { "condition": "AND", "key": "resource_name", "operator": "=", "value": "Setting" }
     ]
    }
   ]
  }
 ]
}